### ISSUE TITLE
Compilation fails to build on Windows

### ISSUE THREAD

**Issue by nicholatian** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#16]
![Crash dump](https://cdn.securelateral.net/perm/battle-engine-bug.png "Crash dump")

Seems that you haven’t been testing this on Windows, hmm? Try using cross-platform path separators everywhere.

**Comment by DizzyEggg** [comment]
I've got Windows7 and it works for me

**Comment by mrdollsteak** [comment]
I've been getting this issue! Since I added the Defog and Clear Smog animation. I'm not sure if its because its too big now or if I've bungled something up.
[img]https://snag.gy/rdZTGW.jpg[/img]

**Comment by KDSKardabox** [comment]
This turned out be a non issue. It looks like a case of not following the instructions properly. :P
