### ISSUE TITLE
Use explicit hashbang for Python scripts

### ISSUE THREAD

**Issue by nicholatian** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#17]
People should be able to tell which version of Python the script is to use by looking at the hashbang; `#!/usr/bin/env python` is not sufficiently explicit. On Debian, `python` is Python 2, whereas on Arch it is Python 3. On Windows it’s even worse, and depends on the order in which they were installed (IIRC).

**Comment by DizzyEggg** [comment]
Done
