### ISSUE TITLE
Add .gitignore for C and Python, and…

### ISSUE THREAD

**Issue by nicholatian** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#19]
Add a .gitignore that covers files that should be ignored for both the C and Python languages.

In addition to this, it would also be wise to ignore both `/BPEE0.gba` and `/test.gba` as well as those are very heavyweight files that would hurt the repo if accidentally added.

**Comment by DizzyEggg** [comment]
Added one that covers C and stuff that I keep in the folder while building and testing. Gitignore for Python is nor needed atm, but will be added if a need arises.

**Comment by nicholatian** [comment]
It’s important to ignore directories named `__pycache__` which are generated if you `import` any local Python files. Dunno if you do as of yet, but it’s worth noting IMO.
