### ISSUE TITLE
`chmod a+x scripts/build`, etc.

### ISSUE THREAD

**Issue by nicholatian** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#20]
Git will save the executability attributes of your scripts, so have it remember them.

**Comment by DizzyEggg** [comment]
what do you mean?

**Comment by KDSKardabox** [comment]
No response about how to implement it. Closed for the time being.

**Comment by nicholatian** [comment]
>_> I didn’t get notified of this. Implementing it is easy, but the issue is probably transparent to both of you because you’re on Windows.

Windows is by and large ignorant of this, but UNIX-based operating systems have a little more intellect behind how they decide whether a file is executable. Contrary to Windows, which decides based on the ending of the file name, UNIX suggests that implementations use file attributes to dictate the readability, writability, and executability of a given file. On GNU/Linux, OS X, and *BSD, the command to change these attributes is called `chmod`.

People on these systems cannot run your scripts on the command-line unless they’re marked as executable. So basically, every time we need to run the build script, we have to pre-emptively run `chmod a+x scripts/build` et cetera and *then* execute them. If we’re working from a cloned snapshot, this dirties the repo.

Fortunately, Git automatically tracks the read/write/execute attributes of every file in the repo; you just need to `chmod` the file to be executable by the world using the `a+x` option (meaning all-add-executability) and Git can add it to the repo as a commit. Obviously, you will need a UNIX-based operating system to do this as far as I’m aware, unless there is some hack that lets you do this on Windows.
