### ISSUE TITLE
Perform newline normalisation on source files

### ISSUE THREAD

**Issue by nicholatian** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#21]
![Newlines wrong](http://cdn.securelateral.net/perm/battle-engine-issues.png "Newlines wrong")

For some reason, cloning this repo in Git (using GNU/Linux) does not normalise the files for me. Whenever I clone something of mine on Linux, it has `\\n` newlines, and on Windows GitHub for Windows normalises them as `\\r\\n`. Clearly this is not the case with this repo.

You should study the different things you can put into a `.gitattributes` file to fix this.

**Comment by nicholatian** [comment]
Just noted this, but it seems only `/scripts/build` has this issue. The other scripts were normalised.

**Comment by DizzyEggg** [comment]
Not anymore. Buahahahaha
