### ISSUE TITLE
Expanded Pokémon have broken moves

### ISSUE THREAD

**Issue by Tetrable** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#24]
Using the engine with an expanded ROM. Tested expanded slots by adding Darkrai in. Moves seemed to be jumbled up, even if using moveset offset of a Pokémon which doesn't have a jumbled movepool in-game. I'm assuming this is a problem from the engine.

![bpe2](https://cloud.githubusercontent.com/assets/15126835/18401168/0bf55ef2-76d1-11e6-8231-0ad0e1eb4c7e.png)

**Comment by DizzyEggg** [comment]
Sorry, I was afk on IRC. Not really a problem, we have the movesets, they're just not added to the table. See the learnsets.c file

**Comment by Tetrable** [comment]
Thanks! I've gotten it to work.

![bpe2](https://cloud.githubusercontent.com/assets/15126835/18409752/aad29456-7747-11e6-810c-7d229a0e13db.png)
