### ISSUE TITLE
Bug or i'm doing something wrong? 

### ISSUE THREAD

**Issue by raven1910** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#28]
I downloaded last build. Build it, insert succesfully. And without changes in PGE or G3T, vanilla rom, i seen a invalid moves effects. More about issue - https://youtu.be/ldxrsLte8Tc . Maybe i faild with something. Maybe new offset for moves i must been inserted. I don't know. But the rom without changes after building. Maybe it's not a bug. Sorry for my english. And thank you.

**Comment by DizzyEggg** [comment]
Yeah, KDS did something to Birch battle, gonna look into it

**Comment by DizzyEggg** [comment]
Fixed
