### ISSUE TITLE
Cherrim and Castform Ability Changing

### ISSUE THREAD

**Issue by Deokishisu** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#32]
Cherrim should automatically revert to Overcast Form if its ability is changed while it is in its in Sunshine Form.

Castform should be stuck in its current form if its ability is changed. If it regains Forecast, it will then change to the correct form immediately, even if it's already in the correct form, and its type changes again (so it overrides type changes from Camouflage, a Skill Swapped Color Change) even if it's already the correct type.

**Comment by DizzyEggg** [comment]
This was done some time ago
