### ISSUE TITLE
Disable byte replacement isn't doing anything

### ISSUE THREAD

**Issue by NewDenverCity** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#33]
[This line](https://github.com/KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade/blob/master/bytereplacement#L46) doesn't do anything, as that's the same code that is in vanilla Emerald.

**Comment by DizzyEggg** [comment]
Fixed

**Comment by KDSKardabox** [comment]
We'll this is important in case of updates. I'll explain this in IRC if you want to know.
