### ISSUE TITLE
Tickle [Clear Body] X White Herb Bugs 

### ISSUE THREAD

**Issue by raven1910** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#39]
So... Hi :D  it's just me. Came here to show you mini mini bugs or issues, whatever.
---
Tickle [Clear Body] X White Herb Bugs
https://youtu.be/JiC_D3LzY9s
---
Battling in the Battle Frontier, random enemies and maybe random bugs. But White Herb really crash my game. And Tickle used on my metagross with Clear Body ability (Tough Claws it's ok on Mega Gross) also freeze my game. It shows on video aswell :)

**Comment by DizzyEggg** [comment]
Thanks for identifying those! Both should be fixed now.
