### ISSUE TITLE
Double Battle rollout game freeze

### ISSUE THREAD

**Issue by Monukenokara** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#40]
If your opponent uses rollout in a double battle, the animation is bugged and the next level up freezes the game.
https://my.mixtape.moe/ylqbol.webm

**Comment by Monukenokara** [comment]
Doesn't occur with battle animations off

**Comment by DizzyEggg** [comment]
Doesn't happen to me at all. Could you paste about 40 bytes from 2CD75E?

**Comment by Monukenokara** [comment]
`00 97 27 00 5A 27 00 4A 27 0A 03 28 01 0C 0C 08 03 75 0F 11 08 02 00 05 03 89 63 0D 08 02 05 00 00 01 00 1E 00 01 00 00 00 02 58 73 59 08 04 04 00 00 00 00 01 00 02 00 19 8D 00 3F 05 0B 03 0D`

It could be something on my end but I haven't touched animations in my rom at all (possible I've damaged something by accident though)

**Comment by KDSKardabox** [comment]
I assume this is resolved too.
