### ISSUE TITLE
Sticky web doesn't proc when the player 'shifts'

### ISSUE THREAD

**Issue by Monukenokara** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#41]
If you're in 'shift' mode, and you faint an opponent, then use the free switch you will be unaffected by sticky web (I haven't tested other hazards)

**Comment by DizzyEggg** [comment]
I'm unable to replicate that glitch. Sticky Web works fine for me. Are you sure you didn't switch into a flying-type pokemon or a one with Levitate?

**Comment by Monukenokara** [comment]
I swapped in a marshtomp.

I'll close this for now and re-open if I can reproduce.
