### ISSUE TITLE
Volt switch still allows switching against a ground type

### ISSUE THREAD

**Issue by Monukenokara** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#42]
NPC trainer used volt switch, i switched in a ground type and the move does no damage, but still switches afterwards.

**Comment by DizzyEggg** [comment]
Fixed.
https://github.com/KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade/commit/a5ab5a80177ece424f23d708d0a49556c772c998
