### ISSUE TITLE
Clear smog can miss

### ISSUE THREAD

**Issue by Monukenokara** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#43]
No real comment necessary, multiple misses with clear smog in multiple different battles.

**Comment by DizzyEggg** [comment]
Fixed I think https://github.com/KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade/commit/e9d096c2705e34b53674b42bc614b7dad0798eaa
