### ISSUE TITLE
Installation scripts broken

### ISSUE THREAD

**Issue by Touched** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#54]
There are numerous errors in the installation scripts. They make far too many assumptions about users' configuration and operating system.

For example, in the build script:

```python
PATH = 'C://devkitPro//devkitARM//bin'
PREFIX = '//arm-none-eabi-'
AS = (PATH + PREFIX + 'as')
CC = (PATH + PREFIX + 'gcc')
LD = (PATH + PREFIX + 'ld')
```

If the user has changed the installation path for devkitARM, they must edit this script. You should rely on the DEVKITARM or PATH environment variables instead. Currently this path assumes that the user is using Windows and has installed DevkitARM in the default location, which is not true for everyone. Also why are you using double forward slashes? Those are completely unnecessary.

**Comment by KDSKardabox** [comment]
F u betch

**Comment by KDSKardabox** [comment]
Fixed :P
