### ISSUE TITLE
Problem with PGEinidump.py

### ISSUE THREAD

**Issue by Zero123999** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#55]
when running PGEinidump.py there's an error stating that it can't find learnsetcatch

**Comment by KDSKardabox** [comment]
make sure you run the insert.py script before the PGEinidump command that will create a learnsetcatch file in your directory.

**Comment by Zero123999** [comment]
But in instructions it says only do make.py
O well better change the instructions

**Comment by Zero123999** [comment]
./src\bs_start_attack.c: In function 'check_mega_evo':
./src\bs_start_attack.c:414:29: error: 'KEYSTONE' undeclared (first use in this function)
             u16 MEGA_RING = KEYSTONE;
                             ^~~~~~~~
What does this mean
