### ISSUE TITLE
Other languages support

### ISSUE THREAD

**Issue by EddyHg80** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#57]
Hi everyone,

I would like to add these features to an Emerald (I) rom: if I change every single offset in the BPEE.id, bytereplacement, functionrewrites, hooks, repoints, routinepointers files, should everything work? Are there even more offsets I have to change?

Or should I wait for this to have an all in one .ini file so people could contribute to support other languages?

**Comment by DizzyEggg** [comment]
Theoretically you'd only have to change the offsets. But there is lots of them, so figuring all of them out would take very long time. For now, we won't support other language versions.

**Comment by EddyHg80** [comment]
I'm going to do it by myself don't worry ;)

**Comment by Gamer2020** [comment]
@EddyHg80 I think it might be easier to use the English ROM.

**Comment by EddyHg80** [comment]
@Gamer2020 it probably is, but I really want this to work with the italian rom, so at least I'll try. Also all the offsets I "translate" might be useful for other people, so not really a waste of time.
