### ISSUE TITLE
Double Battle Pressure

### ISSUE THREAD

**Issue by DizzyEggg** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#6]
In a double battle(didn't check single) the pressure message loops over forever. Also poke name displayed in the message is wrong.

**Comment by KDSKardabox** [comment]
Geez, I'll look into it.

**Comment by KDSKardabox** [comment]
Corrected message buffers. Unable to replicate the looping issue in doubles

**Comment by DizzyEggg** [comment]
Oops sorry, I've been adding entry hazards and messed something up in the process.

**Comment by KDSKardabox** [comment]
Try checking the switchincounter of battle_stuff_ptr

**Comment by KDSKardabox** [comment]
Accidentally, clicked close

**Comment by KDSKardabox** [comment]
Try checking the position and value  of switchin counter of battle_stuff_ptr in your system

**Comment by DizzyEggg** [comment]
So I fixed it by adding a check. if (!check) do entry message and check = 1;
