### ISSUE TITLE
AI Sticky Web typo?

### ISSUE THREAD

**Issue by BuffelSaft** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#66]
Just had a quick glance through TrainerAI.c, in the function tai6A_discouragehazards you've got

`case MOVE_SPIDER_WEB:
        if (new_battlestruct->side_affecting[side].sticky_web)
            to_sub = 10;
        break;`

Should this be using MOVE_STICKY_WEB instead?

**Comment by KDSKardabox** [comment]
Yes, this should be sticky_web. Fixed! Thanks for identifying.

**Comment by DizzyEggg** [comment]
What a funny typo xd
