### ISSUE TITLE
poke_species typo?

### ISSUE THREAD

**Issue by BlackWhiteRobin** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#67]
Latest build doesn't let me compile the code, specifically 'double_wild_battles.c'.

I checked with an older build 'poke_species' was changed to just 'species' just in the part of calc_ball_formula so I changed it around, made every occurrence of 'poke_species' into 'species' and it compiled just fine.

**Comment by DizzyEggg** [comment]
Thanks for letting me know, fixed
