### ISSUE TITLE
Wrong Mat Block Effect?

### ISSUE THREAD

**Issue by BlackWhiteRobin** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#69]
The move Mat Block isn't supposed to be a damaging move and should block incoming attacks, but that's not what is happening. It damages the opponent and doesn't fail when used more than one time. Was this intended or there was a typo?

If this was intended, sorry. I thought all Gen VI moves were done. :/

**Comment by KDSKardabox** [comment]
We'll be looking into this. Actually, there is no proper track of what ability or move effect is left. So it might be the case that we miss something. 

This one though looks like wrong effect ID mapped to the move in the move table.

**Comment by DizzyEggg** [comment]
Yes, it had a wrong script ID and I forgot to add a first turn only check. And yes, all Gen VI moves are done, this one just happened to have a wrong script ID. :P
