### ISSUE TITLE
Choosing a move causes either ball throw or run from a battle

### ISSUE THREAD

**Issue by DizzyEggg** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#7]
WTF, I just updated the base I use and got this.

**Comment by DizzyEggg** [comment]
bc_preattacks is responsible for this, gonna comment this out till it's fixed

**Comment by KDSKardabox** [comment]
Does it happen with moves like scratch etc.?

**Comment by KDSKardabox** [comment]
It was happening with draco meteor even before I inserted this.

**Comment by DizzyEggg** [comment]
Strange, it only happened to me after hooked bc_preattacks. Tho I didn't test draco meteor

**Comment by KDSKardabox** [comment]
Literally one character was the cause of all this mess. Resolved.
