### ISSUE TITLE
Catching a Pokemon with Disguise leaves it in Busted Form

### ISSUE THREAD

**Issue by ZnogyroP** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#71]
I reported this on Pokecommunity but I figured I should leave it here to ensure it gets fixed. At the moment, if you capture a Pokemon with the ability Disguise after it turns into Busted Form, that Pokemon will stay in Busted Form in the PC. It will not turn back into its standard form until after you've battled with it at least once. The same applies to the ability Stance Change, but with Blade Form.

**Comment by DizzyEggg** [comment]
Fixed in last update!
