### ISSUE TITLE
Cute Charm Fainting Issue

### ISSUE THREAD

**Issue by Trev2** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#73]
If a Pokémon has Cute Charm and infatuates an attacker on the same turn that the Cute Charm Pokémon faints, the attacking Pokémon will remain infatuated despite the Cute Charm Pokémon not being present.

**Comment by DizzyEggg** [comment]
I'm having troubles replicating it. Could you post more details?

**Comment by igorfs10** [comment]
If a Pokémon uses a physical move and causes a pokemon with cute charm to faint, it has a chance to be infatuated. I used Low Kick with Mankey that has vital spirit against wild Jigglypuff.

**Comment by KDSKardabox** [comment]
Fixed!
