### ISSUE TITLE
Wally Catching Sequence

### ISSUE THREAD

**Issue by Trev2** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#74]
Wally's Zigzagoon now 2HKOs the Ralts in the catching sequence.

**Comment by igorfs10** [comment]
This happens sometimes without engine. Have you tried more than once?

**Comment by DizzyEggg** [comment]
That's because Tackle has 10 more BP. You can easily fix it by lowering the Zigzagoon's level.
