### ISSUE TITLE
Sheer Force doesn't remove added effects

### ISSUE THREAD

**Issue by ZnogyroP** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#79]
Found this earlier, when my Sheer Force Nidoqueen's Bulldoze still dropped the opponent's speed. I'm not sure if it's just for 100% moves or what.

**Comment by KDSKardabox** [comment]
This bug actually hides even a bigger bug. That if a move with a secondary effect fails to execute its effect due to Sheer Force or Shield Dust the game crashes. Looking into it.

**Comment by KDSKardabox** [comment]
Fixed!
