### ISSUE TITLE
Draining Kiss Bug

### ISSUE THREAD

**Issue by The-Elite-MYT** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#9]
Draining Kiss seems to be bugged in the latest version (worked ok before). The first use seems to be ok, but when used a second time it causes the graphics to glitch out.

See the video for what I mean. The video shows two examples as I wasn't sure if Trick Room was a contributing factor or not. As it did the same thing in the second battle, I guess it is just DK.

[https://www.youtube.com/watch?v=lTxl_AIM-g0](url)

**Comment by jiangzhengwenjz** [comment]
You can use this one:
'00 ED 27 00 A3 27 00 2F 27 0A 03 2A 01 0C 0C 08 02 74 72 59 08 02 05 01 00 01 00 00 00 08 00 7F 7E 05 02 F0 3A 59 08 82 02 00 00 E8 FF 19 C8 00 3F 05 04 04 03 AD 51 0D 08 02 05 01 00 03 00 00 00 06 00 01 00 0E 09 10 2D 08 05 04 00 0E DF 79 2D 08 05 02 74 72 59 08 02 05 01 00 01 00 08 00 00 00 7F 7E 05 0B 03 0D 08'

**Comment by KDSKardabox** [comment]
It seems to be working fine in a vanilla ROM.

**Comment by The-Elite-MYT** [comment]
Strange. Could have been rectified in a later version. The original one I had was fine, but the latest one I got (with trick room stuff added) bugged out when used more than once in a row.

I'll download the latest version later and see if it's working or not on that.

**Comment by DizzyEggg** [comment]
It sometimes glitches out graphics. Try Ai using it and fainting one of your Pokemon.

**Comment by mrdollsteak** [comment]
I think it might be because there isn't the uh healing particles that happens with like Giga Drain afterwords. Must not be clearing the thing. I'll give it a go making a working one.

**Comment by The-Elite-MYT** [comment]
Dizzy, it was doing the same thing whether it was the AI or me.

I have just got around to downloading the latest version and gave it a quick test. It doesn't seem to be doing it any more, although I only had time to try quickly. Possibly it's ok now.

**Comment by DizzyEggg** [comment]
Draining Kiss has been fixed some time ago. Closing
